### ISSUE TITLE
[windows][caffe] Caffe Framework

### ISSUE THREAD

**Issue by luncliff** [AlcheraInc/vcpkg#1]
### Summary

Windows에서 Caffe 라이브러리/툴을 보다 쉽게 빌드할 수 있도록 port가 추가되었습니다.

[공식버전](https://github.com/BVLC/caffe/releases/tag/1.0)이 지나치게 오래되었기에, [Microsoft/caffe](https://github.com/microsoft/caffe)의 일부와 합치고 CMake를 대대적으로 수정하여 x64 Windows Static(`x64-windows-static`) 조건에서 사용이 가능하도록 한 버전입니다.

Ubuntu/Mac OS 환경은 컴파일러 이슈가 발생할 가능성이 높으므로 다른 방법을 사용해서 빌드하는 것을 권합니다. 필요에 따라 작업하도록 하겠습니다.

### Caution

* Ubuntu/Mac OS 환경 미 지원
* OpenBLAS 사용
* GPU-Only 모드(`USE_CUDA`)
* Boost Python 과 OpenCV 미 사용

```cmake
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBLAS=Open
        -DBUILD_python=OFF
        -DUSE_OPENCV=OFF
        -DUSE_OPENMP=OFF
        -DUSE_LMDB=ON
        -DUSE_LEVELDB=ON
        -DBUILD_docs=OFF
        -DBUILD_matlab=OFF
        -DPROTOBUF_PROTOC_EXECUTABLE:FILEPATH=${PROTOC_EXE_PATH}
        -DCMAKE_INSTALL_PREFIX:FILEPATH=${CURRENT_PACKAGES_DIR}
)
```

### Prerequisite

System environment variable로 `CUDA_PATH`, `CUDA_BIN_PATH`가 모두 필요합니다.
공식 CUDA installer를 사용해 설치하면 `CUDA_PATH`는 설정되지만, `CUDA_BIN_PATH`는 설정되지 않습니다.

![image](https://user-images.githubusercontent.com/14101523/53314720-2df18980-3903-11e9-8f0e-383e9d3a8bd9.png)

사진과 같이 설정한 후, vcpkg에서 CUDA를 설치하는 것으로 `find_package(CUDA)`를 사용할 수 있습니다.

```console
PS D:\vcpkg> ./vcpkg.exe install cuda:x64-windows-static
```

Caffe와 달리, CUDA는 dynamic으로도 사용이 가능합니다.

```console
PS D:\vcpkg> ./vcpkg.exe install cuda:x64-windows
```

### Install

```console
PS D:\vcpkg> ./vcpkg.exe install caffe:x64-windows-static
```

### Not found: ProtocolBuffer Lite 

`vcpkg/installed/x64-windows-static/share/protobuf/protobuf-module.cmake` 에서 해당 모듈 제거. (Windows에서는 사용하지 않음)

```cmake
# ...

#
# Main.
#

# By default have PROTOBUF_GENERATE_CPP macro pass -I to protoc
# for each directory where a proto file is referenced.
if(NOT DEFINED PROTOBUF_GENERATE_CPP_APPEND_PATH)
  set(PROTOBUF_GENERATE_CPP_APPEND_PATH TRUE)
endif()

# The Protobuf library
_protobuf_find_libraries(Protobuf protobuf)

# The Protobuf Lite library
# _protobuf_find_libraries(Protobuf_LITE protobuf-lite) #       <---- comment this line

# The Protobuf Protoc Library
_protobuf_find_libraries(Protobuf_PROTOC protoc)

if(UNIX)
  _protobuf_find_threads()
endif()

# ...
```

**Comment by luncliff** [comment]
현재 사내에 Caffe를 사용하시는 분이 계시면 피드백을 받고 싶습니다. @kisuya @just-hjkwon

**Comment by just-hjkwon** [comment]
출장 중이라 3월 5일 이후에 대응 할 수 있을 것 같습니다. @luncliff
